export enum BookCategory {
  TEXTBOOK = 'TEXTBOOK',
  REFERENCE = 'REFERENCE',
  JOURNAL = 'JOURNAL',
  MAGAZINE = 'MAGAZINE',
  FICTION = 'FICTION',
  NON_FICTION = 'NON_FICTION',
  RESEARCH_PAPER = 'RESEARCH_PAPER',
  OTHER = 'OTHER',
}
